Repository DSC-JSS-NOIDA/QuickLearn, pull requests merged in 2022-05, with the labels that each got.

#174 fix-text-overflow
  css/styles.css
Labels: GSSoC22, Level1

#287 Removed the bug in the categories section
  resource.html
Labels: GSSoC22, Level1

#292 Made sidebar dark in dark mode
  css/styles.css
  js/index.js
Labels: GSSoC22, Level2

#300 Added projects under mern
  data/domains/web/mern/projects.json
  js/getResource.js
  resource.html
Labels: GSSoC22

#296 Added some extra Java resources
  data/domains/programming/java/advanced.json
  data/domains/programming/java/beginner.json
  data/domains/programming/java/intermediate.json
Labels: GSSoC22, Level1

#315 added relevant plaeholder text
  css/styles.css
  index.html
Labels: GSSoC22, Level1
